- name: Install packages (apt)
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - albert
    - bash-completion
    - bash-builtins
    - coreutils
    - curl
    - git
    - gzip
    - htop
    - hh
    - manpages
    - mpv
    - nmap
    - powertop
    - tar
    - synaptic
    - tree
    - terminator
    - vim
    - vim-common
    - vlc
    - rsync
    - wget
    - zip
